# Generated by Django 2.1.1 on 2018-10-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('temail', models.TextField()),
                ('femail', models.TextField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('venue', models.TextField()),
                ('link', models.BinaryField()),
                ('contact', models.TextField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
    ]
